# To test / verify
# macOS / Linux:
# $ docker run -ti -v "$PWD:$PWD" -w "$PWD" goreleaser/goreleaser:latest release --snapshot --clean
# windows (Git bash):
# $ MSYS_NO_PATHCONV=1 docker run -ti -v "$PWD:$PWD" -w "$PWD" goreleaser/goreleaser:latest release --snapshot --clean

version: 2

project_name: olla

before:
  hooks:
    - go mod download
    - mkdir -p config logs tmp data
    - cp config-base/config.yaml config/config.yaml
    - cp config-base/docker.yaml config/docker.yaml
    - cp config-base/models.yaml config/models.yaml
    - cp config-base/config.yaml default.yaml
    - touch data/.gitkeep
    - touch logs/.gitkeep
    - touch tmp/.gitkeep

release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
  draft: false
  prerelease: auto
  make_latest: true

snapshot:
  name_template: '{{ incpatch .Version }}-{{.ShortCommit}}'

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goamd64:
      # https://github.com/golang/go/wiki/MinimumRequirements#amd64
      - v1
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X "github.com/thushan/olla/internal/version.Version=v{{.Version}}"
      - -X "github.com/thushan/olla/internal/version.Commit={{.Commit}}"
      - -X "github.com/thushan/olla/internal/version.Date={{.CommitDate}}"
      - -X "github.com/thushan/olla/internal/version.User=goreleaser"
#    asmflags:
#      - all=-trimpath={{ dir (default "." .Env.PWD) }}
#    gcflags:
#      - all=-trimpath={{ dir (default "." .Env.PWD) }}


dockers:
  - image_templates:
      - "ghcr.io/thushan/olla:latest"
      - "ghcr.io/thushan/olla:{{ .Tag }}"
      - "ghcr.io/thushan/olla:v{{ .Major }}"
      - "ghcr.io/thushan/olla:v{{ .Major }}.{{ .Minor }}"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.description=High-performance LLM front-end load balancer and proxy"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
    extra_files:
      - config/
      - logs/.gitkeep
      - default.yaml

checksum:
  name_template: "checksums.txt"

archives:
  - files:
      - LICENSE
      - readme.md
      - config/**
      - data/.gitkeep
      - logs/.gitkeep
      - tmp/.gitkeep
      - default.yaml
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
    name_template: >-
      {{ .ProjectName }}_v{{- .Version }}_{{- if eq .Os "darwin" }}macos_{{- else }}{{ .Os }}_{{ end }}{{- .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^Merge"