# Olla Configuration (docker)
# This file is used to configure the Olla server and its components for Docker deployment.
# By default, it uses the host for Ollama and LM Studio instances.
server:
  host: "localhost"
  port: 40114
  read_timeout: 20s
  write_timeout: 0s # for LLMs streaming, leave this as 0s
  shutdown_timeout: 10s
  request_logging: true
  request_limits:
    max_body_size: 52428800  # 50MB
    max_header_size: 524288  # 512KB
  rate_limits:
    global_requests_per_minute: 1000
    per_ip_requests_per_minute: 100
    health_requests_per_minute: 1000
    burst_size: 50
    per_endpoint:
      default_requests_per_minute: 200
    cleanup_interval: 5m
    trust_proxy_headers: false
    trusted_proxy_cidrs: [
      "127.0.0.0/8",
      "10.0.0.0/8",
      "172.16.0.0/12",
      "192.168.0.0/16"
    ]

proxy:
  engine: "sherpa"
  connection_timeout: 40s
  response_timeout: 900s
  read_timeout: 300s
  max_retries: 3
  retry_backoff: 500ms
  load_balancer: "priority" # Available: round_robin, least_conn, priority
  stream_buffer_size: 8192

discovery:
  type: "static"
  refresh_interval: 30s
  static:
    endpoints:
      - url: "http://host.docker.internal:11434"
        name: "local-ollama"
        type: "ollama"
        priority: 100
        model_url: "/api/tags"
        health_check_url: "/"
        check_interval: 5s
        check_timeout: 2s
      - url: "http://host.docker.internal:1234"
        name: "local-lm-studio"
        type: "lm-studio"
        priority: 100
        model_url: "/v1/models"
        health_check_url: "/"
        check_interval: 5s
        check_timeout: 2s
  model_discovery:
    enabled: true
    interval: 5m
    timeout: 30s
    concurrent_workers: 5
    retry_attempts: 3
    retry_backoff: 1s

model_registry:
  type: "memory"

logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, file

engineering:
  show_nerdstats: false